### ISSUE TITLE
Как вы тренировали сеть?

### ISSUE THREAD

**Issue by arvbs** [sovse/base_rus_whisper_stt#1]
Здравствуйте. Только разбираюсь с whisper. Подскажите, а как вы тренировали сеть, чтобы создать base_rus.pt. 

Везде ищу, не могу найти. С нуля получается нельзя сделать? Только на слабо обученной модели Whisper - Tiny например? Т.е. это только получается добавление, а не обучение заново?

Спасибо вам заранее за ответ.

**Comment by sovse** [comment]
Здравствуйте. С нуля думаю можно обучать, но нужен огромный датасет и большой Гпу кластер....
Тренировал я его, используясь пример отсюда.
https://colab.research.google.com/drive/1P4ClLkPmfsaKn2tBbRp0nVjGMRKR-EWz?usp=sharing
